name: Run Appium Tests with Allure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download sample APK
        run: |
          curl -o /tmp/app.apk https://github.com/appium/sample-code/blob/master/sample-code/apps/ApiDemos/bin/ApiDemos-debug.apk?raw=true

      - name: Start Appium Server
        run: |
          npm install -g appium
          appium --log appium.log &
          sleep 10

      - name: Run Appium test
        run: |
          mkdir -p reports
          pytest tests/ || true  # để bước sau vẫn chạy ngay cả khi test fail

      - name: Upload Allure Report Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: reports

      - name: Upload Appium Logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: appium-log
          path: appium.log
